---
- hosts: dev
  become: True
  tasks:
    - name: Run the container
      docker_container:
        name: hassan-app
        image: "hassanali70826/myapp:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8081:8081
